import type { NextPage } from "next";

import { trpc } from "../utils/trpc";
import Head from "next/head";
import Link from "next/link";

// import BatchRenderer from "../components/BatchRenderer";
import DocumentRenderer from "../components/DocumentRenderer";

const Dashboard: NextPage = () => {
  // const batchFetch = trpc.useQuery(["article.batch-data"]);
  const documentFetch = trpc.useQuery(["article.document-data"]);
  console.log(documentFetch.data);

  return (
    <>
      <Head>
        <title>Pulth App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="bg-slate-200 h-12  w-screen px-12 flex justify-between items-center">
        <Link href="/">Pulth</Link>
        <div className="flex gap-4">
          <Link href="#">
            <div className="p-1.5 rounded-md  border border-slate-400">
              Login
            </div>
          </Link>
          <Link href="#">
            <div className="p-1.5 rounded-md  border border-slate-400">
              Register
            </div>
          </Link>
        </div>
      </nav>
      <main className="w-full p-5 sm:w-11/12 md:w-10/12 lg:w-9/12 xl:w-8/12 mx-auto">
        {documentFetch.data ? (
          <DocumentRenderer data={documentFetch.data} />
        ) : null}
      </main>
    </>
  );
};

export default Dashboard;
