import type { NextPage } from "next";

import { trpc } from "../utils/trpc";
import Head from "next/head";
import Link from "next/link";

import { useSession } from "next-auth/react";
import ProfileNavbar from "../components/ProfileNavbar";

import DashboardLayout from "../components/layouts/dashboard";

const Explore: NextPage = () => {
  // const batchFetch = trpc.useQuery(["article.batch-data"]);

  const { data } = useSession();
  const user = data?.user;

  return (
    <DashboardLayout>
      <Head>
        <title>Pulth App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="bg-slate-200 h-12 px-12 flex justify-between items-center">
        <Link href="/">Pulth</Link>
        <div className="flex gap-4 items-center">
          {user ? (
            <ProfileNavbar user={user} />
          ) : (
            <>
              <Link href="/api/auth/signin">
                <a className="p-1.5 rounded-md  border border-slate-400">
                  Login
                </a>
              </Link>
              <Link href="#">
                <a className="p-1.5 rounded-md  border border-slate-400">
                  Register
                </a>
              </Link>
            </>
          )}
        </div>
      </nav>
    </DashboardLayout>
  );
};

export default Explore;
