import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { trpc } from "../utils/trpc";
import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import FacebookIcon from "../components/icons/FacebookIcon";
import TwitterIcon from "../components/icons/TwitterIcon";
import { MapPinIcon, PhoneIcon } from "@heroicons/react/24/outline";

const Home: NextPage = () => {
  const ref = useRef(null);
  const ref2 = useRef(null);
  const ref3 = useRef(null);
  const isInView = useInView(ref, { once: true });
  const isInView2 = useInView(ref2, { once: true });
  const isInView3 = useInView(ref3, { once: true });
  return (
    <div className="bg-gray-900">
      <Head>
        <title>Pulth App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="bg-slate-800 w-full hidden sm:flex lg:flex p-4 align-middle items-center sticky top-0 z-20">
        <span className="text-indigo-500 text-2xl font-bold mr-auto self-stretch my-auto">
          PulthApp
        </span>
        <div className="sm:flex items-center hidden gap-x-8">
          <Link href={"/explore"}>
            <button className="text-white p-2 text-xl font-semibold">
              Explore
            </button>
          </Link>
          <Link href={"/courses"}>
            <button className="text-white p-2 text-xl font-semibold">
              Courses
            </button>
          </Link>
          <Link href={"/articles"}>
            <button className="text-white p-2 text-xl font-semibold">
              Articles
            </button>
          </Link>
          <Link href="/api/auth/signin">
            <button className="text-indigo-500 p-2 rounded text-xl font-bold">
              Join Now!
            </button>
          </Link>
        </div>
      </nav>
      <main className="flex flex-col overflow-x-hidden">
        <div className="flex flex-col lg:flex-row lg:justify-between justify-center sm:px-28 lg:px-16 sm:pt-8 lg:pt-0 items-center bg-gray-900 h-screen">
          <motion.div
            initial="hidden"
            animate="visible"
            variants={{
              hidden: {
                opacity: 0,
                x: -100,
              },
              visible: {
                opacity: 1,
                x: 0,
                transition: {
                  delay: 0.5,
                  duration: 0.5,
                },
              },
            }}
            className="lg:w-3/4"
          >
            <div className="flex flex-col h-full p-4 lg:p-8 gap-y-5 font-slab tracking-tighter w-full justify-center items-center">
              <p className="lg:text-6xl sm:text-5xl text-4xl text-white font-bold leading-tight lg:text-left text-center">
                <span className="text-indigo-500">Pulth</span> is the new way of
                learning.
                <br className="lg:block hidden" /> Now it&apos;s your time to{" "}
                <span className="text-indigo-500">learn</span> with quality!
              </p>
              <div className="w-fit lg:w-full">
                <Link href="/api/auth/signin">
                  <button className="text-white lg:text-3xl p-3 bg-indigo-500 font-semibold rounded-lg">
                    Join for free
                  </button>
                </Link>
              </div>
            </div>
          </motion.div>
          <motion.div
            className="lg:block sm:hidden block"
            initial="hidden"
            animate="visible"
            variants={{
              hidden: {
                opacity: 0,
                x: 100,
              },
              visible: {
                opacity: 1,
                x: 0,
                transition: {
                  delay: 0.8,
                  duration: 0.6,
                },
              },
            }}
          >
            <Image
              src="/undraw_online_learning_re_qw08.svg"
              height={800}
              width={800}
              alt="learning"
            />
          </motion.div>
          <motion.div
            className="lg:hidden sm:block hidden"
            initial="hidden"
            animate="visible"
            variants={{
              hidden: {
                opacity: 0,
                x: 100,
              },
              visible: {
                opacity: 1,
                x: 0,
                transition: {
                  delay: 0.8,
                  duration: 0.6,
                },
              },
            }}
          >
            <Image
              src="/undraw_online_learning_re_qw08.svg"
              height={600}
              width={600}
              alt="learning"
            />
          </motion.div>
        </div>
        <div className="lg:mb-0 mb-12 flex sm:gap-y-12 gap-y-0 lg:gap-y-0 flex-col lg:flex-row-reverse justify-center lg:justify-between sm:px-28 lg:px-16 lg:pt-16 items-center bg-gray-900 h-screen snap-center">
          <div
            className="opacity-60 transition-all ease-in-out duration-200 lg:duration-500 lg:delay-500 flex flex-col lg:h-full h-full p-4 lg:p-8 gap-y-5 font-slab tracking-tighter w-full lg:w-3/4 justify-center lg:items-start items-center sm:h-fit"
            style={{
              transform: isInView ? "none" : "translateX(200px)",
              opacity: isInView ? 1 : 0,
            }}
            ref={ref}
          >
            <p className="lg:text-6xl sm:text-5xl text-4xl text-white font-bold leading-tight text-center lg:text-left">
              You can <span className="text-indigo-500">learn for free </span>
              by reading articles written by our community!
            </p>
            <div>
              <Link href="/articles">
                <button className="text-white lg:text-3xl p-3 bg-indigo-500 font-semibold rounded-lg">
                  View Articles
                </button>
              </Link>
            </div>
          </div>
          <div
            className="transition-all delay-200 duration-500 lg:delay-700 lg:duration-700 ease-in-out"
            ref={ref}
            style={{
              transform: isInView ? "none" : "translateX(-200px)",
              opacity: isInView ? 1 : 0,
            }}
          >
            <Image
              src="/undraw_knowledge_re_5v9l.svg"
              height={800}
              width={800}
              alt="learning"
              className="-translate-x-6 lg:mr-0"
            />
          </div>
        </div>
        <div className="flex flex-col gap-y-12 lg:gap-y-0 lg:flex-row justify-center lg:justify-between sm:px-28 lg:px-16 lg:pt-16 sm:pt-0 pt-16 items-center bg-gray-900 h-screen">
          <div
            className="transition-all ease-in-out duration-200 lg:duration-500 lg:delay-500 flex flex-col h-full sm:h-fit lg:h-full p-4 lg:p-8 gap-y-5 font-slab tracking-tighter w-full lg:w-3/4 justify-center lg:items-start items-center"
            style={{
              transform: isInView2 ? "none" : "translateX(-200px)",
              opacity: isInView2 ? 1 : 0,
            }}
            ref={ref2}
          >
            <p className="lg:text-6xl text-4xl text-white font-bold leading-tight text-center lg:text-left">
              We are giving you the privilege of learning from
              <span className="text-indigo-500"> verified teachers </span>
              chosen by our algorithm!
            </p>
            <div>
              <Link href={"/courses"}>
                <button className="text-white lg:text-3xl p-3 bg-indigo-500 font-semibold rounded-lg">
                  View Courses
                </button>
              </Link>
            </div>
          </div>
          <div
            className="transition-all delay-200 duration-500 lg:delay-700 lg:duration-700 ease-in-out"
            style={{
              transform: isInView2 ? "none" : "translateX(200px)",
              opacity: isInView2 ? 1 : 0,
            }}
          >
            <Image
              src="/undraw_video_streaming_re_v3qg.svg"
              height={800}
              width={800}
              alt="learning"
            />
          </div>
        </div>
        <div className="flex flex-col justify-center p-4 sm:px-28 lg:px-16 items-center bg-gray-900 h-screen">
          <div
            className="transition-all ease-in-out duration-200 lg:duration-500 lg:delay-500 flex flex-col lg:p-4 pb-0 gap-y-6 font-slab tracking-tighter h-fit justify-center items-center"
            style={{
              transform: isInView3 ? "none" : "translateX(-200px)",
              opacity: isInView3 ? 1 : 0,
            }}
            ref={ref3}
          >
            <p className="lg:text-6xl text-4xl text-white font-bold leading-tight text-center">
              Go ahaead and <span className="text-indigo-500">explore</span>{" "}
              what we offer to you!
            </p>
            <div>
              <Link href={"/explore"}>
                <button className="text-white lg:text-3xl p-3 bg-indigo-500 font-semibold rounded-lg">
                  Explore
                </button>
              </Link>
            </div>
          </div>
          <div
            className="transition-all delay-200 duration-500 lg:delay-700 lg:duration-700 ease-in-out"
            style={{
              transform: isInView3 ? "none" : "translateX(200px)",
              opacity: isInView3 ? 1 : 0,
            }}
            ref={ref3}
          >
            <Image
              src="/undraw_adventure_re_ncqp.svg"
              height={600}
              width={600}
              alt="learning"
            />
          </div>
        </div>
      </main>
      <footer className="bg-gradient-to-b from-gray-900 via-black to-black flex gap-y-12 flex-col lg:flex-row justify-between p-4 lg:p-12 lg:px-24 pt-64 font-slab">
        <div className="flex flex-col lg:w-1/3 justify-center gap-y-5">
          <h3 className="text-white text-2xl font-bold">
            <span className="text-indigo-600">Pulth</span>App
          </h3>
          <p className="text-white">
            PulthApp is the new way of learning with free and priced options.
            You can read articles for free that made by our community. Second
            option is you can buy courses that made in a predetermined
            curriculum by verified teachers from our community.
          </p>
          <div className="flex flex-col text-white gap-y-6">
            <div className="flex items-center gap-x-4">
              <FacebookIcon className="fill-white" />
              <p className="font-semibold">@pulthappfacebook</p>
            </div>
            <div className="flex items-center gap-x-4">
              <TwitterIcon className="fill-white" />
              <p className="font-semibold">@pulthapptwitter</p>
            </div>
          </div>
        </div>
        <div className="flex flex-col lg:w-1/3 lg:items-center text-white gap-y-6">
          <h3 className="text-2xl font-semibold">Useful Links</h3>
          <Link href={"/explore"}>
            <a className="cursor-pointer text-sm">Explore</a>
          </Link>
          <Link href={"/courses"}>
            <a className="cursor-pointer text-sm">Courses</a>
          </Link>
          <Link href={"/articles"}>
            <a className="cursor-pointer text-sm">Articles</a>
          </Link>
        </div>
        <div className="flex flex-col lg:w-1/3 lg:items-center text-white gap-y-6">
          <h3 className="text-white text-2xl font-semibold">Contact</h3>
          <div className="flex gap-x-2 items-center">
            <MapPinIcon className="w-6 h-6" />
            <p className="text-sm">
              26985 Brighton Lane, Lake Forest, CA 92630.
            </p>
          </div>
          <div className="flex gap-x-2 items-center">
            <PhoneIcon className="w-6 h-6" />
            <p className="text-sm">+90 538 865 01 98</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Home;
